### ISSUE TITLE
[BUG] Undefined behavior with `torch.cat`

### ISSUE THREAD

**Issue by egaznep** [pytorch/tensordict#1031]
## Describe the bug

I have the following `@tensorclass`, to store output from a GAN discriminator.

```python
@tensordict.tensorclass
class DiscriminatorOutput:
    score: torch.Tensor
    f_map: Dict[str, torch.Tensor]
```

`score` contains the discriminator output, and `f_map` contains the feature maps. I have an ensemble of discriminators, though I do not use tensordict features to form the ensemble, I just store them in a ModuleList, sequentially call, and store the outputs in a `List[DiscriminatorOutput]` because there are discriminators with different architectures and from what I understood I cannot create an ensemble of different architectures.

Then, I need to concatenate 

## To Reproduce

A MWE:

```python
import torch
import tensordict

from typing import Dict

@tensordict.tensorclass
class DiscriminatorOutput:
    score: torch.Tensor
    f_map: Dict[str, torch.Tensor]

score_shapes = [
    (16, 1, 4101),
    (16, 1, 2452),
]

features = [
    {
        's1': torch.zeros((16, 32, 257, 511)),
        's2': torch.zeros((16, 32, 513, 256)),
    },
    {
        'p1': torch.zeros((16, 1, 44)),
        'p2': torch.zeros((16, 1, 88)),
    },
]

tds = []
for shape_s, f_map in zip(score_shapes, features):
    tds.append(DiscriminatorOutput(score=torch.zeros(shape_s), f_map=f_map, batch_size=[16]))


final = torch.cat(tds, dim=-2)
print(final)
```

```bash
DiscriminatorOutput(
    f_map=NonTensorData(data={'s1': tensor([[[[0.  ...  .., 0., 0., 0.]]]])}, batch_size=torch.Size([32]), device=None),
    score=Tensor(shape=torch.Size([16, 1, 6553]), device=cpu, dtype=torch.float32, is_shared=False),
    batch_size=torch.Size([32]),
    device=None,
    is_shared=False)
```

## Expected behavior

From what I understand, this call to `torch.cat` should not even work, because for TensorDicts it should only support concatenation at `batch_size` dimensions. Other than that, there are a couple of problems with the output:

1) `f_map` only contains the feature maps from the first discriminator (keys: 's1', 's2') but not the subsequent discriminators. (keys: 'f1', 'f2').
2) Result of the concatenation has a `batch_size` of 32, so does `f_map`. On the other hand, score.shape has a `batch_size` of 16, and so does the `f_map` entries.

The output I wish to get is the following, where the score is concatenated at the last dimension, the outputs from each feature map preserved, and the batch_size not changing.:

```bash
DiscriminatorOutput(
    f_map=NonTensorData(data={'s1': tensor([[[[0.  ...  .., 0., 0., 0.]]]]), ..., 'f2': tensor([[[0.  ...  .., 0., 0., 0.]]])}, batch_size=torch.Size([16]), device=None),
    score=Tensor(shape=torch.Size([16, 1, 6553]), device=cpu, dtype=torch.float32, is_shared=False),
    batch_size=torch.Size([16]),
    device=None,
    is_shared=False)
```

## System info

Describe the characteristic of your environment:
 * Describe how the library was installed (pip, source, ...)
 * Python version
 * Versions of any other relevant libraries

```python
import tensordict, numpy, sys, torch
print(tensordict.__version__, numpy.__version__, sys.version, sys.platform, torch.__version__)
```

```bash
import tensordict, numpy, sys, torch
print(tensordict.__version__, numpy.__version__, sys.version, sys.platform, torch.__version__)
0.5.0 2.0.1 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)] win32 2.4.1+cpu
```
(tried with nightly and it gives the same output)

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/tensordict/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by egaznep** [comment]
Hi there, thanks for the quick and elaborate response!

> 1. I understand you want to use dictionaries but not as tensordicts right? Is there a particular reason for that? (storing things as tensordict could come in handy later in the code and usually there are very few API differences with a regular dict) They seem to have the proper batch size and as far as I can tell you want s1, s2, f1 and f2 to have the same batch size as the main dta carrier you displayed in the Expected Behavior section.

> 2. You want to use `cat` along what I would call a feature dimension, not a batch dimension. That's not really what the classes have been designed for (the problem tensordict lib is trying to solve is the 'one-to-many' issue where you want to apply the same op to all the tensors in a collection).

I see.

> For instance, if I was to merge one entry and cat another I would do this
> 
> ```python
> import torch
> import tensordict
> 
> 
> @tensordict.tensorclass
> class DiscriminatorOutput:
>     score: torch.Tensor
>     f_map: tensordict.TensorDict
> 
> score_shapes = [
>     (16, 1, 4101),
>     (16, 1, 2452),
> ]
> 
> features = [
>     {
>         's1': torch.zeros((16, 32, 257, 511)),
>         's2': torch.zeros((16, 32, 513, 256)),
>     },
>     {
>         'p1': torch.zeros((16, 1, 44)),
>         'p2': torch.zeros((16, 1, 88)),
>     },
> ]
> 
> tds = []
> for shape_s, f_map in zip(score_shapes, features):
>     tds.append(DiscriminatorOutput(score=torch.zeros(shape_s), f_map=tensordict.TensorDict(f_map), batch_size=[16]))
> 
> def func(name, v1, v2):
>     if name == "score":
>         return torch.cat([v1, v2], -1)
>     return v1.update(v2)
> 
> td = tds[0].named_apply(func, *tds[1:], call_on_nested=True)
> print(td)
> ```
> 
> giving
> 
> ```
> DiscriminatorOutput(
>     f_map=TensorDict(
>         fields={
>             p1: Tensor(shape=torch.Size([16, 1, 44]), device=cpu, dtype=torch.float32, is_shared=False),
>             p2: Tensor(shape=torch.Size([16, 1, 88]), device=cpu, dtype=torch.float32, is_shared=False),
>             s1: Tensor(shape=torch.Size([16, 32, 257, 511]), device=cpu, dtype=torch.float32, is_shared=False),
>             s2: Tensor(shape=torch.Size([16, 32, 513, 256]), device=cpu, dtype=torch.float32, is_shared=False)},
>         batch_size=torch.Size([16]),
>         device=None,
>         is_shared=False),
>     score=Tensor(shape=torch.Size([16, 1, 6553]), device=cpu, dtype=torch.float32, is_shared=False),
>     batch_size=torch.Size([16]),
>     device=None,
>     is_shared=False)
> ```

Thanks for the solution, I will try it out today. Checking the API, I somehow expected a function like `merge_tensordicts` to implement this behavior. For `TensorDict`s with same name, it currently discards everything but the entry in the last `TensorDict`. Would it make sense to have a `call_on_nested` argument for that function too?

**Comment by vmoens** [comment]
That's a valid point
We have a merge tensordict function, maybe we could pass a kwarg that tells the function what to do when a key already exist?
In your example it'd be
```
merge_tensordict(td0, td1, callback_exist=torch.cat)
```

**Comment by egaznep** [comment]
I noticed your solution would not support more than two `DiscriminatorOutput`s to be merged. So I had to modify things a little:

```python
def temporary_merge_tds(name: str, *v):
    # until TensorDict.merge_tensordict has the new API
    if 'score' == name:
        return torch.cat(v, dim=-1)
    else:
        return tensordict.merge_tensordicts(*v)
```
