### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mctigger** [pytorch/tensordict#1092]
## Describe the bug
@tensorclass casts `float` to a `torch.Tensor` of type `float32` which triggers batch_shape validation errors. Same problem with `int`.

## To Reproduce

```python
from tensordict import tensorclass
import torch

@tensorclass
class MyTensorClass:
    my_float: float
    my_tensor: torch.Tensor


if __name__ == "__main__":
    my_float = 5.0
    my_tensor = torch.tensor([1,2,3])
    # This works
    my_tensor_class = MyTensorClass(my_float, my_tensor)
    # Note: my_float gets casted to a torch.Tensor
    print(my_tensor_class)

    # This fails since batch_shape does not match
    my_tensor_class = MyTensorClass(my_float, my_tensor, batch_size=[3])
```
prints: 
```
MyTensorClass(
    my_float=Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
    my_tensor=Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.int64, is_shared=False),
    batch_size=torch.Size([]),
    device=None,
    is_shared=False)
```
```
RuntimeError: batch dimension mismatch, got self.batch_size=torch.Size([3]) and value.shape=torch.Size([]).
```

## Expected behavior

Non-tensor values should stay non-tensor values.

## System info

Describe the characteristic of your environment:
 * TensorDict version 0.6.2 (bug exists since 0.5 I think)
 * Python version: 3.9

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/tensordict/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
try 
```python
@tensorclass(autocast=True)
class MyTensorClass:
    my_float: float
    my_tensor: torch.Tensor
```
or
```python
@tensorclass(nocast=True)
class MyTensorClass:
    my_float: float
    my_tensor: torch.Tensor
```
on nightlies.

The first one will ensure that all the type annotations are respected (unless they're not plain types, like Optional or Union)
The second will just not cast anything: if it's not a tensor, its type will not be changed.
LMK if that helps!

**Comment by mctigger** [comment]
Thanks a lot! That helps!

I would still change the default behavior to `nocast=True`. Casting as the default behavior is unexpected.
