### ISSUE TITLE
[BUG] Tensordict messes up values of a tensor when casting it between devices and numpy inside a class call.

### ISSUE THREAD

**Issue by LukasKarner** [pytorch/tensordict#1104]
## Describe the bug

This bug occurs in the process of converting a tensor stored in a TensorDict from the mps device to numpy and then converting it again to a tensor and storing it in the TensorDict without explicitly casting it to the mps device again.
Normally, as proven by the last part of the code below, this works fine, but if done inside a class call the values of the tensor are messed up about half of the times.

## To Reproduce

The following code reproduces the bug, multiple executions may be necessary as the bug does not occur always.

```python
import torch
from tensordict import TensorDict


class SomeModel:
    def __call__(self, batch: TensorDict) -> TensorDict:
        output = batch["input"].cpu().numpy()
        print("During:")
        print(output)
        batch["output"] = torch.from_numpy(output) # using ```.to(batch.device)``` fixes the problem
        return batch

device = torch.device("mps")

model = SomeModel()

x = TensorDict({"input": torch.ones(10)}).to(device)
print("Before:")
print(x["input"])

x = model(x)
print("After:")
print(x["output"])


# in a normal setting the same code works fine without having to send the tensor to the device
x["t1"] = torch.ones(10).to(device)
n = x["t1"].cpu().numpy()
x["t2"] = torch.from_numpy(n)
print("Normal:")
print(x["t2"])

```

About half of the times the code works out fine where all the tensors/arrays have the same values and the output looks like this:
```bash
Before:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='mps:0')
During:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
After:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='mps:0')
Normal:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='mps:0')
```

But the other times somethings gets messed up in the ```x["result"]``` tensor and the output might look like some of these:
```bash
Before:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='mps:0')
During:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
After:
tensor([6.1528e+19, 1.4013e-45, 1.5602e+20, 1.4013e-45, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00], device='mps:0')
Normal:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='mps:0')
```

```bash
Before:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='mps:0')
During:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
After:
tensor([0.0000e+00, 0.0000e+00, 2.1887e+28, 1.4013e-45, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00], device='mps:0')
Normal:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='mps:0')
```

```bash
Before:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='mps:0')
During:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
After:
tensor([6.5203e+09, 1.4013e-45, 0.0000e+00, 0.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00], device='mps:0')
Normal:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='mps:0')
```

## Expected behavior

I am not exactly sure whether the bug actually is the problem described above (i.e. messed up tensors when not casting the tensor to the right device), or the fact that one can add tensors to TensorDicts with different devices and not having to cast them to the right device in the first place.
So, I would either expect an exception or warning to be raised when adding tensors to TensorDicts with different devices, or that the assignment works without messing up the values.

## System info

 * OS: (main, Oct  4 2024, 15:57:01) [Clang 17.0.6 ] darwin
 * Library: conda-forge
 * Python version: 3.12.7
 * Tensordict version: 0.5.0
 *  Numpy: 1.26.4
 * Torch version: 2.5.0

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/tensordict/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Hello
This op is done synchronously (`tensor.to(device, non_blocking=False)`) within [_validate_value](https://github.com/pytorch/tensordict/blob/bbfe8c7fbb3e52c162cb39c44ed71f9c4d45723d/tensordict/base.py#L9396)

I can't reproduce it on my M3 but I trust that you're seeing this, it seems related to this: 
https://github.com/pytorch/pytorch/issues/139550#issuecomment-2468860559

The simplified code here would be

```python
import torch
n = 1_000_000

x = torch.ones(n).to("mps") # maybe also created directly on mps
y = x.cpu().numpy()
assert (torch.from_numpy(y).to("mps") == 1).all()
```
( I can't reprod with this on my computer either )

Note that in your normal setting you don't have the final `to("mps")`: in tensordict, `TensorDict.to(device)` registers the device and then all tensors placed in it will be moved synchronously to that device. If you do `clear_device_` this behaviour will be revoked.

cc @malfet

**Comment by LukasKarner** [comment]
Hello,
(and sorry for the late reply!)

Yes, I forgot to metion my hardware: 2021 MacBook Pro with M1 Pro and MacOS 15.1.1

The code snippet you included works fine for me; also if I wrap it in a class call like with my original issue.

As for:
> Note that in your normal setting you don't have the final ```to("mps")```

Yes, that is precisely what I meant when I discussed the expected behaviour.
I was not sure if it is OK that it works without the final ```to("mps")``` or if this should raise a warning or error already.

**Comment by vmoens** [comment]
Oh and can you try with a more recent version of tensordict?

**Comment by LukasKarner** [comment]
I installed tensordict 0.6.2 now and with it I cannot reproduce the bug anymore👍🏼
