### ISSUE TITLE
[Feature Request] Add a `conda` install option for `tensordict` on conda-forge channel

### ISSUE THREAD

**Issue by sugatoray** [pytorch/tensordict#280]
A conda installation option could be very helpful. I have already started working on this, to add `tensordict` to conda-forge.

Conda-forge PR: 

- https://github.com/conda-forge/staged-recipes/pull/22307

Once the conda-forge PR is merged, you will be able to install the library with conda as follows:

```sh
conda install -c conda-forge tensordict
```

:bulb: I will push a PR to update the docs once the package is available on conda-forge.

**Comment by sugatoray** [comment]
@vmoens Please assign this to me, as I am already working on this one.

**Comment by sugatoray** [comment]
`tensordict` is available on conda-forge.

cc: @vmoens

**Comment by vmoens** [comment]
@sugatoray I'm not very well versed in the dark magic of conda*
Could you help me by either updating the release to 0.4 or better - tell me how to do it in the future? Thanks!


I just pip install everything and when i'm really really forced to use conda, I run a `conda create env` and while it's running I rewrite a proof of Fermat's last theorem

**Comment by sugatoray** [comment]
@vmoens Let me check the conda-forget recipe. I will keep you posted. Please mention me here if do not hear from me by next week Friday.

**Comment by sugatoray** [comment]
@vmoens I have opened an issue to track the progress of this update. 

- https://github.com/conda-forge/tensordict-feedstock/issues/9

**Comment by sugatoray** [comment]
@vmoens TensorDict has been updated to latest version on conda-forge.
