### ISSUE TITLE
[Minor] Typing of `key` should be `NestedKey` rather than `str`?

### ISSUE THREAD

**Issue by FrankTianTT** [pytorch/tensordict#548]
## Describe the bug

Should we adjust all `key` typing from `str` to `NestedKey`? For example:
```python
def rename_key_(self, old_key: str, new_key: str, safe: bool = False) -> T:
```
should be 
```python
def rename_key_(self, old_key: NestedKey, new_key: NestedKey, safe: bool = False) -> T:
```

## To Reproduce

The type check will give an error, for example the code of [`DreamerModelLoss`](https://pytorch.org/rl/_modules/torchrl/objectives/dreamer.html#DreamerModelLoss):
```python
tensordict.rename_key_(("next", "reward"), ("next", "true_reward"))
```

## Reason and Possible fixes

I'll be happy to change these if needed:)

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/tensordict/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Yep definitely 
I was planning to make this a part of a big refactoring of the lib (better doc and docstrings) but we could anticipate the change if anyone's up to it!
