### ISSUE TITLE
[Feature Request] Support specifying group in `isend` and `irecv`

### ISSUE THREAD

**Issue by lucifer1004** [pytorch/tensordict#615]
## Motivation

Currently, `isend` and `irecv` do not have a `group` argument, making it impossible to specify the desired communication group when there are multiple groups.

An example is when using a NCCL-based group for GPU communication, while also using a GLOO-based group for CPU communication.

## Solution

Add a `group` argument to `isend` and `irecv`, and pass the parameter down to the underlying `torch.distributed` methods.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by vmoens** [comment]
Good point will take care of vat today unless you want to do it :)

**Comment by lucifer1004** [comment]
@vmoens I just submitted a PR but have not added tests yet, since I am not familiar with the test environment settings of this project.

**Comment by vmoens** [comment]
I can help with that! Do you mind if I edit your PR directly?
