### ISSUE TITLE
[BUG] pad_sequence raises an error when return_mask=True

### ISSUE THREAD

**Issue by dtsaras** [pytorch/tensordict#643]
## Describe the bug

While the pad_sequence function works, when the flag return_mask is set to True, it raises an error. 

## To Reproduce

```python
from tensordict import TensorDict, pad_sequence

list_td = [TensorDict({"a": torch.zeros((3,))}, []), TensorDict({"a": torch.zeros((4,))}, [])]
padded_td = pad_sequence(list_td, return_mask=True, batch_first=True)
```

```bash
Traceback (most recent call last):
  File "/Users/dtsaras/Documents/CS/circuit_gen/test.py", line 37, in <module>
    padded_td = pad_sequence(list_td, batch_first=True, return_mask=True)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/c_gen/lib/python3.10/site-packages/tensordict/tensordict.py", line 5717, in pad_sequence
    raise RuntimeError(f"pad_sequence failed for key {key}") from err
RuntimeError: pad_sequence failed for key mask
```

## Expected behavior

A TensorDict with a "mask" key that contains a bool tensor where the entries with padded_val should be the padded entries in the corresponding padded sequence. 

## System info

Describe the characteristic of your environment:
 * Install with pip install tensordict
 *  Python version 3.10

```python
import tensordict, numpy, sys, torch
print(tensordict.__version__, numpy.__version__, sys.version, sys.platform, torch.__version__)
```
0.2.1 1.26.2 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ] darwin 2.1.2

## Additional context

Another potential improvement in the current implementation is that we might need multiple mask for every different key name {key}_mask

## Reason and Possible fixes

The issue starts in the file tensordict/tensordict.py, line 5685 (if return_mask:). The issue is that the mask is created by using the shape td.shape, where in the case of a single TensorDict, it has a size of torch.Size([]), so it create a mask that is torch.tensor(True). The fixing would be to either completely remove this option, or create a mask for every key in the TensorDict and then create a mask of the appropriate size. 

## Checklist

- [Yes] I have checked that there is no similar issue in the repo (**required**)
- [Yes] I have read the [documentation](https://github.com/pytorch/tensordict/tree/main/docs/) (**required**)
- [Yes] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Closed by #652
