### ISSUE TITLE
[BUG] Functional call with TensorDictParams is slow

### ISSUE THREAD

**Issue by vmoens** [pytorch/tensordict#668]
Because it ends up calling `tensordict.update` which performs a lot of checks (and does so recursively) the following call is much slower with this class than with a regular tensordict:
```python
with tdparams.to_module(module):
    module(x)
```
If module is narrow but deep, most of the time is spent during the `TensorDictBase.__exit__` method.

The culprit is https://github.com/pytorch/tensordict/blob/751091a1fe22ce727d1db181c3000777aa9c4c49/tensordict/_td.py#L431-L436

## Solution: low hanging fruit

The easiest thing to do is to call `update` only once (and not for each level of nesting, which repeats the same operation a million times).

## Ad-hoc solution

We should carefully think about the best way to repopulate the tensordict during exit. The core problem is that a call to `module.forward` may change the parameters or buffers out-place, so we need to gather them back and place them back in the original tensordict. Unpacked, the code looks like
```python
prev_params = tdparams.to_module(module)
module(x)
maybe_updated_params = prev_params.to_module(module)
tdparams.update(maybe_updated_params)
```

One thing we could do is update the params iif their identity has changed (otherwise they are already updated / untouched). That will require some checks but better than calling update every time.

cc @matteobettini

**Comment by matteobettini** [comment]
i think in the last code block there is a typo: shouldn't the `to_module ` be `from_module`?

**Comment by matteobettini** [comment]
> One thing we could do is update the params iif their identity has changed (otherwise they are already updated / untouched). That will require some checks but better than calling update every time.

How can we check if they have changed without looking at all of them?
