### ISSUE TITLE
[BUG] @tensorclass.to_dict() removes non-tensor entries.

### ISSUE THREAD

**Issue by maximilianigl** [pytorch/tensordict#706]
## Describe the bug

When using a tensorclass, the `to_dict()` method removes non-tensor data. 
Similarly, `.items()` also doesn't iterate over non-tensor data.

## To Reproduce

```python
from tensordict.prototype import tensorclass

@tensorclass
class TestClass:
  my_tensor: torch.Tensor
  my_str: str
  
test_class = TestClass(
  my_tensor=torch.tensor([1, 2, 3]),
  my_str="hello",
  batch_size=[3]
)

print(test_class.to_dict())

for k, v in test_class.items():
  print(k, v)
```

Output:
```
{'my_tensor': tensor([1, 2, 3])}
my_tensor tensor([1, 2, 3])
```

## Expected behavior

Expected Output:
```
{'my_tensor': tensor([1, 2, 3]), 'my_string': 'hello'}
my_tensor tensor([1, 2, 3])
my_str 'hello'
```

## System info

Using tensordict==0.3.1

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/tensordict/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by maximilianigl** [comment]
I assume it's because non-tensor data doesn't yet make use of the ability to add non-tensor data to the tensordict, but is instead added to `test_class._non_tensordict`?

**Comment by vmoens** [comment]
On it! Should be easy to fix
