### ISSUE TITLE
[BUG] Out of date pip install for python 3.12 / Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by tiagorpereira** [pytorch/tensordict#766]
## Describe the bug

While testing the latest Ubuntu 24.04 LTS and pytorch 2.3.0, pydict is not updated on PyPI for python 3.12. Doing the normal install, the newest version is 0.1.2 (nightly also only has updates till 2023-06). 

I tried to force 0.4.0 install using `pip install pydict==0.4.0` but is not listed.

## To Reproduce

1. Fresh install pytorch 2.3.0 and pydict from PyPI on Python 3.12.3.
2. Try running any codes that has functions after pydict version 0.1.2 (like MemoryMappedTensor)
3. Error is raised that couldn't import MemoryMappedTensor because it doesn't exist.

## Expected behavior

Import would work as expected and no errors raised.

I tested on python 3.11.9 and everything worked as expected.

## System info

- System: Ubuntu 24.04 LTS
- Python version: 3.12.3
- PyPI 24.0
- pytorch 2.3.0

**Comment by yklcs** [comment]
Is there anything blocking support for Python 3.12? I tried installing from source and everything seems to work.
Looks like 3.12 wheels are only for macOS on PyPI.

**Comment by kurtamohler** [comment]
pydict is unrelated to tensordict. Nevertheless, installing tensordict 0.4.0 does indeed fail with python 3.12:

```bash
conda create -n torchrl-test
conda activate torchrl-test
conda install python==3.12
pip install tensordict==0.4.0
```

```
ERROR: Could not find a version that satisfies the requirement tensordict==0.4.0 (from versions: 0.0.1a0, 0.0.1b0, 0.0.1rc0, 0.0.2a0, 0.0.2b0, 0.0.3, 0.1.0, 0.1.1, 0.1.2)
ERROR: No matching distribution found for tensordict==0.4.0
```
