### ISSUE TITLE
Implemented Operations between two TensorDicts are defined by their position in their respective trees, not their keys

### ISSUE THREAD

**Issue by ludwigwinkler** [pytorch/tensordict#853]
## Describe the bug

For example, the __add__ function is implemented between two tensordicts.
Yet which of the leaves of two tensordicts are added is determined by their position in the respective tensordicts, not their explicit keys.

## To Reproduce

```python
import torch
from tensordict import TensorDict

x0 = TensorDict(
    {
        "y": torch.tensor([1.0, 0.1, -0.1]),
        "x": torch.tensor([-1.0, 0.1, 0.0]),
    }
)

x1 = TensorDict(
    {
        "x": torch.tensor([-1.0, 0.1, 0.0]),
        "y": torch.tensor([2.0, 0.1, -0.1]),
    }
)

print(f"+: ", (x0 + x1).to_dict())
print(f"*: ", (x0 * x1).to_dict())
```
Output:
```
+:  {'y': tensor([ 0.0000,  0.2000, -0.1000]), 'x': tensor([ 1.0000,  0.2000, -0.1000])}
*:  {'y': tensor([-1.0000,  0.0100, -0.0000]), 'x': tensor([-2.0000,  0.0100, -0.0000])}
```

Here the leaves are processed irrespective of their key.
Thus position in the tree trumps the keys.

## Additional context

I just became aware of `tensordict.apply()` which should probably be used instead and implements a `tree_map()` functionality? 

As far as I can tell, maybe the `add` functionality here should use an items() iterator which sortes the values by their keys?
https://github.com/pytorch/tensordict/blob/6165e77ad096b56c1be394c8ca63faad5c55b001/tensordict/base.py#L7026

**Comment by vmoens** [comment]
On it
