### ISSUE TITLE
[BUG] Iterating through keys for a tensordict seems to fail with runtime error on stopIteration

### ISSUE THREAD

**Issue by demmerichs** [pytorch/tensordict#959]
## Describe the bug

```python
td = TensorDict(dict(a=1,b=2))
for k in td:
    print(k)
```

fails with a runtime error reporting that the generator raised a stop iteration.

## Expected behavior

Just print the keys, iterate normally.

## System info

Describe the characteristic of your environment:
 * Describe how the library was installed (pip, source, ...)
 * * pip
 * Python version
 * * 3.11.4
 * Versions of any other relevant libraries

```python
import tensordict, numpy, sys, torch
print(tensordict.__version__, numpy.__version__, sys.version, sys.platform, torch.__version__)
```
results in
```
0.5.0 1.26.4 3.11.4 (main, Jun  7 2023, 18:32:58) [GCC 10.2.1 20210110] linux 2.4.0+cu121
```

## Reason and Possible fixes

https://stackoverflow.com/questions/51700960/runtimeerror-generator-raised-stopiteration-every-time-i-try-to-run-app

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/tensordict/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
We had to choose between:

`td.__iter__ = dict.__iter__`

and

`td.__iter__ = Tensor.__iter__`.

and decided for the latter.

This will work

```python
td = TensorDidct(a=torch.randn(3), batch_size=[3])
for _td in td:
    assert not _td.batch_size
```

You can iter using `keys` and `items` or `values`.

Also, this will work

```python
"a" in td
```

**Comment by demmerichs** [comment]
Ok thanks for the super quick response. I see the problem...
@vmoens quick follow-up: regarding default collate of pytorchs dataloader, what would be the way to go?
It detects tensordict as mapping, and tries to iterate over the keys, collating for each key separately, where it then fails with above error.

Is there some collate_fn I can provide the dataloader with, implemented in tensordict? Is there a plan to add this to the default_collate_fn_map in pytorch?

**Comment by vmoens** [comment]
Tell it `collate_fn=lambda x=x`, that should work

**Comment by vmoens** [comment]
IF (big wish here) we upstream tensordict to PyTorch I'll make sure this is part of the package ;)

**Comment by demmerichs** [comment]
Ok, I tested collate_fn=identity as you suggested, but with my dataset returning a tensordict without batch dimension, this leads to dataloader to just produce a list of tensordicts, with the length of the list being the specified number of batch elements.

This worked for me:
```python
from tensordict import TensorDict
from torch.utils.data._utils.collate import default_collate_fn_map

def collate_td(tds, *, collate_fn_map=None):
    return torch.stack(tds)

default_collate_fn_map.update({TensorDict: collate_td})
```

**Comment by vmoens** [comment]
That was going to be my suggestion! Glad that it worked

**Comment by vmoens** [comment]
Usually the way I suggest to use data loaders is to pass the tensordict as the dataset. I'm working on a dataset zoo, hopefully things will be clearer when this is in the doc!
